services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
      - ./AirbnbData:/var/lib/postgresql/AirbnbData
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.1"
    user: "${UID}:${GID}"  
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/db
      - ./AirbnbData:/data/AirbnbData
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.1"

